version: 0.0
os: linux
files:
  - source: /
    destination: /var/app/
permissions:
  - object: /**/*
    # mode: 755
    # pattern: "**"
    owner: root
    group: root
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: root
  # BeforeInstall:
  #   - location: ../../../../../../scripts/before_install.sh
  #     timeout: 300
  #     runas: ec2-user
  # ApplicationStart:
  #   - location: ../../scripts/application_start.sh
  #     timeout: 300
  #     runas: ec2-user
